Sabemi/Sabemi.Admin/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sabemi.Admin.Models;
using Sabemi.Domain.Entities.Admin;
using Sabemi.Domain.Interfaces;
using Sabemi.Domain.Interfaces.Services;
using static Sabemi.CrossCutting.Util.Enumerator;

namespace Sabemi.Admin.Controllers
{
    public class AdminUserController : MainController
    {
        private readonly IAdminUserService _service;
        private readonly ILogger<AdminUserController> _logger;
        private readonly IMapper _mapper;

        public AdminUserController(INotification notification,
                                   IAdminUserService userService,
                                   ILogger<AdminUserController> logger,
                                   IMapper mapper) : base(notification)
        {
            _service = userService;
            _logger = logger;
            _mapper = mapper;
        }

        [Route("usuarios")]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(JQueryDataTableParamModel param)
        {
            List<string[]> data = new List<string[]>();
            string filter = param.sSearch ?? string.Empty;
            try
            {
                int start = param.iDisplayStart + 1;
                int end = param.iDisplayStart + param.iDisplayLength;
                var result = _mapper.Map<List<AdminUserViewModel>>(await _service.GetAll(filter, start, end));

                foreach (var item in result)
                {
                    int inactive = item.Active ? 0 : 1;

                    data.Add(new string[]
                    {
                        item.Profile,
                        item.Login,
                        item.LastAccess.ToShortDateString(),
                        item.Id + "#" + inactive.ToString(),
                        item.Id.ToString()
                    });
                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            JsonResult retorno = Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = data.Count,                
                iTotalDisplayRecords = await _service.GetTotalRecords(filter),
                aaData = data
            });

            return retorno;
        }

        [Route("novo-usuario")]
        public IActionResult Create(AdminUserViewModel model)
        {
            model.Profiles = EnumExtensions.GetAll<ProfileEnum>();
            model.Profile = model.IdProfile.ToEnum<ProfileEnum>().Description();
            return View(model);
        }

        [Route("editar-usuario/{id}")]
        public async Task<IActionResult> Edit(string id)
        {
            var adminUser = _mapper.Map<AdminUserViewModel>(await _service.Get(id));
            if (adminUser == null)
                return NotFound();

            return View(adminUser);
        }

        [HttpPost]
        public async Task<IActionResult> Save(AdminUserViewModel model)
        {
            ModelState.Remove("NewPassword");
            string action = string.IsNullOrEmpty(model.Id) ? "Create" : ModelState.Remove("Password") ? "Edit" : "";            
            if (!ModelState.IsValid)
            {
                Notify("Preencha todas as informações!");
                return CustomRedirect(action, model);
            }

            var admin = new AdminUser();
            if (string.IsNullOrEmpty(model.Id))
                admin = _mapper.Map<AdminUser>(model);
            else
            {
                admin = await _service.Get(model.Id);
                admin.Cod_Login = model.Login;
                admin.Dta_Atualizacao = DateTimeOffset.Now;
                admin.Cod_Nivel_Acesso = model.IdProfile.ToEnum<ProfileEnum>().ToString();
                admin.Sta_Ativo = model.Active;
            }

            if (string.IsNullOrEmpty(model.Id))
                await _service.Insert(admin);
            else await _service.Update(admin);

            if (!CheckOperationSuccess("Dados Salvos com Sucesso"))
                return CustomRedirect(action, model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task Inactivate(string id, bool inativo)
        {
            var adminUser = await _service. Get(id);
            adminUser.Sta_Ativo = !inativo;
            await _service.Update(adminUser);
        }
    }
}

Sabemi/Sabemi.Admin/Controllers/AssistedModeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sabemi.Admin.Models;
using Sabemi.Domain.Entities.Admin;
using Sabemi.Domain.Interfaces;
using Sabemi.Domain.Interfaces.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Sabemi.Admin.Controllers
{
    public class AssistedModeController : MainController
    {
        private readonly ILogger<AssistedModeController> _logger;
        private readonly IAssistedModeService _service;

        public AssistedModeController(INotification notification,
                                      ILogger<AssistedModeController> logger,
                                      IAssistedModeService service) : base(notification)
        {
            _logger = logger;
            _service = service;
        }

        [Route("modo_assistido")]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(JQueryDataTableParamModel param)
        {
            IList<string[]> data = new List<string[]>();
            string filter = param.sSearch ?? string.Empty;

            try
            {
                int start = param.iDisplayStart + 1;
                int end = param.iDisplayStart + param.iDisplayLength;

                IList<AssistedMode> result = await _service.GetAll(filter, start, end);
                foreach (var item in result)
                {
                    data.Add(new string[]
                    {
                        item.Cod_Ip,
                        item.Cod_Descricao
                    });
                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            JsonResult retorno = Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = await _service.GetTotalRecords(filter),
                iTotalDisplayRecords = data.Count,
                aaData = data
            });

            return retorno;
        }

        [Route("novo_ip_modo_assistido")]
        public IActionResult Create()
        {
            return View();
        }

        [Route("novo_ip_modo_assistido")]
        [HttpPost]
        public async Task<IActionResult> Create(AssistedMode assistedMode)
        {
            if (!ModelState.IsValid)
            {
                Notify("Preencha todas as informações!");
                return CustomView(assistedMode);
            }

            assistedMode.Cod_Id = Guid.NewGuid().ToString();
            await _service.Insert(assistedMode);
            if (!CheckOperationSuccess("Dados Salvos com Sucesso"))
                return CustomRedirect("Create", assistedMode);

            return RedirectToAction(nameof(Index));
        }
    }
}

Sabemi/Sabemi.Admin/Controllers/PortalAccessController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sabemi.Admin.Models;
using Sabemi.Domain.Interfaces;
using Sabemi.Domain.Interfaces.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Sabemi.Admin.Controllers
{
    public class PortalAccessController : MainController
    {
        private readonly ILogger<PortalAccessController> _logger;
        private readonly IPortalAccessService _service;
        private readonly IMapper _mapper;

        public PortalAccessController(INotification notification,
                                      ILogger<PortalAccessController> logger,
                                      IPortalAccessService service,
                                      IMapper mapper) : base(notification)
        {
            _logger = logger;
            _service = service;
            _mapper = mapper;
        }

        [Route("acessos_portal")]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AccessList(JQueryDataTableParamModel param)
        {
            List<string[]> data = new List<string[]>();
            string filter = param.sSearch ?? string.Empty;

            try
            {
                int start = param.iDisplayStart + 1;
                int end = param.iDisplayStart + param.iDisplayLength;

                var result = _mapper.Map<List<PortalAccessViewModel>>(await _service.GetAccessPortal(filter, start, end));

                foreach (var item in result)
                {
                    var status = item.Blocked ? 0 : 1;

                    data.Add(new string[]
                    {
                        item.Date.ToShortDateString(),
                        item.Hour,
                        item.CPF,
                        item.IP,
                        item.Id + "#" + status.ToString()
                    });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            JsonResult retorno = Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = data.Count,
                iTotalDisplayRecords = await _service.GetTotalRecords(filter),
                aaData = data
            });

            return retorno;
        }

        [HttpGet]
        public async Task Blocked(string id, bool inativo)
        {
            var client = await _service.GetClient(id);
            client.Sta_Bloqueado = !inativo;
            await _service.UpdateClient(client);
        }
    }
}

Sabemi/Sabemi.Admin/Controllers/WhiteListController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sabemi.Admin.Models;
using Sabemi.Domain.Entities.Admin;
using Sabemi.Domain.Interfaces;
using Sabemi.Domain.Interfaces.Services.Admin;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Sabemi.Admin.Controllers
{
    public class WhiteListController : MainController
    {
        private readonly ILogger<WhiteListController> _logger;
        private readonly IWhiteListService _service;

        public WhiteListController(INotification notification, ILogger<WhiteListController> logger, IWhiteListService service) : base(notification)
        {
            _logger = logger;
            _service = service;
        }
        
        [HttpGet("whitelist")]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(JQueryDataTableParamModel param)
        {
            IList<string[]> data = new List<string[]>();
            string filter = param.sSearch ?? string.Empty;

            try
            {
                int start = param.iDisplayStart + 1;
                int end = param.iDisplayStart + param.iDisplayLength;

                IList<WhiteList> result = await _service.GetAll(filter, start, end);
                foreach (var item in result)
                {                    
                    data.Add(new string[]
                    {
                        item.Cod_Ip,
                        item.Cod_Descricao
                    });
                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            JsonResult retorno = Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = await _service.GetTotalRecords(filter),
                iTotalDisplayRecords = data.Count,
                aaData = data
            });

            return retorno;
        }

        [HttpGet("novo_ip_whitelist")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("novo_ip_whitelist")]
        public async Task<IActionResult> Create(WhiteList whiteList)
        {
            if (!ModelState.IsValid)
            {
                Notify("Preencha todas as informações!");
                return CustomView(whiteList);
            }

            whiteList.Cod_Id = Guid.NewGuid().ToString();
            await _service.Insert(whiteList);
            if (!CheckOperationSuccess("Dados Salvos com Sucesso"))
                return CustomRedirect("Create", whiteList);

            return RedirectToAction(nameof(Index));
        }
    }
}

Sabemi/Sabemi.Admin/Views/Shared/_Layout.cshtml
@using Sabemi.Domain.Interfaces
@inject IAuthUser authUser
<!DOCTYPE html>
<html class="gt-ie8 gt-ie9 not-ie">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>@ViewBag.Title &raquo; Sabemi Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="sname" content="@Environment.MachineName">

    <style>
        .select2-hidden-accessible {
            display: none;
        }
    </style>
    <link rel="icon" href="@Url.Content("~/images/favicon.ico")" type="image/x-icon" />

    <partial name="_StylesPartial" />

    <meta name="description" content="Admin" />
</head>

<!-- BODY  -->
<body class="theme-dust main-menu-animated main-navbar-fixed main-menu-fixed no-main-menu hide">

    <div class="btns-selection active">
        <div class="twitter-select">
            <!-- Go to www.addthis.com/dashboard to customize your tools -->
            <div class="addthis_sharing_toolbox"></div>

        </div>
        <a href="#" class="comment-select">
        </a>
    </div>
    <script>

        var init = [];
    </script>

    <div id="main-wrapper">

        <!-- MAIN_NAVIGATION -->
        <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
            <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>

            <div class="navbar-inner">
                <div class="navbar-header">
                    <a asp-action="Index" asp-controller="Home" class="navbar-brand">
                        <img src="@Url.Content("~/images/logo.png")" alt="Sabemi Admin" style="margin: 2px 0 5px;height: 40px;"> &nbsp;
                    </a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>
                </div>
                <!-- navbar-header -->

                <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
                    <div>

                        

                        <ul class="nav navbar-nav">
                            <li><a asp-action="Index" asp-controller="AssistedMode"><i class="menu-icon fa fa-list-alt"></i> <span class="mm-text">IP's Modo Assistido</span></a></li>
                            <li><a asp-action="Index" asp-controller="PortalAccess"><i class="menu-icon fa fa-list-ul"></i> <span class="mm-text">Acessos ao Portal</span></a></li>
                            <li><a asp-action="Index" asp-controller="AdminUser"><i class="menu-icon fa fa-users"></i> <span class="mm-text">Usuários</span></a></li>
                            <li><a asp-action="Index" asp-controller="PortalClient"><i class="menu-icon fa fa-group"></i> <span class="mm-text">Clientes</span></a></li>
                            <li><a asp-action="Index" asp-controller="WhiteList"><i class="menu-icon fa fa-user"></i> <span class="mm-text">IP's de Exceção (WhiteList)</span></a></li>
                            <li><a asp-action="Index" asp-controller="BlockedAccess"><i class="menu-icon fa fa-ban"></i> <span class="mm-text">Acessos Bloqueados</span></a></li>
                            <li><a asp-action="Index" asp-controller="AdminConfiguration"><i class="menu-icon fa fa-gears"></i> <span class="mm-text">Configurações</span></a></li>
                        </ul>
                        <!-- navbar-nav -->

                        <div class="right clearfix">
                            <ul class="nav navbar-nav pull-right right-navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                                        <i class="fa fa-male"></i>
                                        <span>@authUser.GetUserName()</span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        @*<li>
                                            <a asp-action="ChangePassword" asp-controller="Account"><i class="dropdown-icon fa fa-key"></i>&nbsp;&nbsp;Alterar Senha</a>
                                        </li>*@
                                        <li class="divider"></li>
                                        <li>
                                            <a asp-action="Logout" asp-controller="Account"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Sair</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <!-- navbar-nav -->
                        </div>
                        <!-- right -->
                    </div>
                </div>
                <!-- main-navbar-collapse -->
            </div>
            <!-- navbar-inner -->
        </div>
        <!-- main-navbar -->

        <div id="main-menu" role="navigation">
            <div id="main-menu-inner">
                <div class="menu-content top animated fadeIn">
                    <div>
                        <div class="text-bg"><span class="text-semibold"></span></div>
                    </div>
                </div>
                <ul class="navigation"></ul>

                <!-- navigation -->
            </div>
            <!-- main-menu-inner -->
        </div>
        <!-- main-menu -->
        <!-- MAIN_MENU -->
        <div id="loader" style=""></div>
        <div id="content-wrapper">
            @RenderBody()
        </div>
        <!-- content-wrapper -->
        <div id="main-menu-bg"></div>
    </div>

    <!-- Large modal -->
    <div id="modal-view" class="modal fade modal-blur" tabindex="-1" role="dialog" style="display: none;">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <a href="#" target="_blank" class="btn btn-labeled btn-primary btn-sm" id="modal-view-link"><span class="btn-label icon fa fa-link"></span>Abrir em nova página</a>
                    <a href="#" target="_blank" class="btn btn-labeled btn-info btn-sm" id="modal-view-copy"><span class="btn-label icon fa fa-copy"></span>Copiar URL</a>
                    <h4 class="modal-title">Vizualização</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12 width-zoom">
                            <div class="frame frame-desktop">
                                <iframe src="about:blank" name="desktop"></iframe>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-md-4 width-zoom">
                            <div class="frame frame-mobile">
                                <iframe src="about:blank" name="mobile"></iframe>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-8 width-zoom">
                            <div class="frame frame-tablet">
                                <iframe src="about:blank" name="tablet"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- modal-content -->
        </div> <!-- modal-dialog -->
    </div> <!-- modal -->
    <!-- Large modal -->
    <!-- main-wrapper -->

    <partial name="_ScriptsPartial" />
    <partial name="_Message" />

    <script type="text/javascript">
        init.push(function () {
            // Javascript code here
            if ($("#jq-datatable_wrapper").length) {
                if ($("#jq-datatable-caption").length) {
                    $('#jq-datatable_wrapper .table-caption').text($("#jq-datatable-caption").text());
                }

                if ($("#jq-datatable-search").length) {
                    $('#jq-datatable_wrapper .DT-search:last').after($("#jq-datatable-search").children());
                }

                $('#jq-datatable_wrapper .dataTables_filter input').attr('placeholder', 'Busca...');
            }

            $('.btn-excluir').on('click', function () {

                var action = $(this).data('url');
                bootbox.confirm("Deseja excluir esse registro?", function (result) {
                    if (result) {
                        location.href = action;
                    }
                })


            });
        });

        window.PixelAdmin.start(init);

    </script>
</body>
</html>

Sabemi/Sabemi.Admin/Views/Shared/_Message.cshtml
@using static Sabemi.CrossCutting.Util.Enumerator

@if (!string.IsNullOrEmpty(TempData["Success"]?.ToString()) || (TempData["Errors"] != null && ((ICollection<string>)TempData["Errors"]).Count > 0))
{
    <script type="text/javascript">
        init.push(function () {
            @if (!string.IsNullOrEmpty(TempData["Success"]?.ToString()))
            {                
                <text>notify('@TempData["Success"].ToString()', '@AdminMessageType.Success');</text>
            }
            else
            {
                @foreach(string err in (ICollection<string>)TempData["Errors"])
                {
                    <text>notify('@err', '@AdminMessageType.Error');</text>
                }
            }
        });
    </script>
}

Sabemi/Sabemi.Admin/Views/Shared/_ScriptsPartial.cshtml
<script src="@Url.Content("~/scripts/jquery-3.2.1.min.js")"></script>
<script src="@Url.Content("~/scripts/bootbox.min.js")"></script>
<script src="@Url.Content("~/scripts/bootstrap.js")"></script>
<script src="@Url.Content("~/scripts/bootstrap-datepicker.js")"></script>
<script src="@Url.Content("~/scripts/bootstrap-datepicker2.js")"></script>
<script src="@Url.Content("~/scripts/bootstrap-editable-demo.js")"></script>
<script src="@Url.Content("~/scripts/clipboard.min.js")"></script>
<script src="@Url.Content("~/scripts/dropzone.js")"></script>
<script src="@Url.Content("~/scripts/helpjs.js")"></script>
<script src="@Url.Content("~/scripts/ie.js")"></script>
<script src="@Url.Content("~/scripts/jquery.cropit.js")"></script>
<script src="@Url.Content("~/scripts/jquery.dataTables.min.js")"></script>
<script src="@Url.Content("~/scripts/jquery.jeditable.min.js")"></script>
<script src="@Url.Content("~/scripts/jquery.mask.min.js")"></script>
<script src="@Url.Content("~/scripts/jquery.maskedinput.min.js")"></script>
<script src="@Url.Content("~/scripts/jquery.maskMoney.js")"></script>
@*<script src="@Url.Content("~/scripts/jquery.min.2.0.3.js")"></script>*@
<script src="@Url.Content("~/scripts/jquery.mockjax.js")"></script>
<script src="@Url.Content("~/scripts/jquery.radios-to-slider.min.js")"></script>
<script src="@Url.Content("~/scripts/jquery.validate.js")"></script>
@*<script src="@Url.Content("~/scripts/jquery-1.10.2.js")"></script>*@
<script src="@Url.Content("~/scripts/jquery-confirm.js")"></script>
<script src="@Url.Content("~/scripts/jquery-form-plugins.js")"></script>
<script src="@Url.Content("~/scripts/jquery-form-ready.js")"></script>
<script src="@Url.Content("~/scripts/jstree.min.js")"></script>
<script src="@Url.Content("~/scripts/Main.js")"></script>
<script src="@Url.Content("~/scripts/Mapa.js")"></script>
<script src="@Url.Content("~/scripts/modernizr-2.6.2.js")"></script>
<script src="@Url.Content("~/scripts/moment.js")"></script>
<script src="@Url.Content("~/scripts/pickmeup.min.js")"></script>
<script src="@Url.Content("~/scripts/respond.js")"></script>
<script src="@Url.Content("~/scripts/respond.matchmedia.addListener.js")"></script>
<script src="@Url.Content("~/scripts/select2.min.js")"></script>
<script src="@Url.Content("~/scripts/summernote.min.js")"></script>
<script src="@Url.Content("~/scripts/tinycolor.min.js")"></script>
<script src="@Url.Content("~/scripts/_references.js")"></script>
<script src="@Url.Content("~/scripts/jquery-ui-extras.js")"></script>
<script src="@Url.Content("~/scripts/select2_locale_pt-BR.js")"></script>
<script src="@Url.Content("~/scripts/pixel-admin.js")"></script>
<script src="@Url.Content("~/scripts/_Admin.js")"></script>

Sabemi/Sabemi.Admin/Views/Shared/_StylesPartial.cshtml
<link rel="stylesheet" href="@Url.Content("~/css/widgets.css")">
<link rel="stylesheet" href="@Url.Content("~/css/_Style.css")">
<link rel="stylesheet" href="@Url.Content("~/css/bootstrap.css")">
<link rel="stylesheet" href="@Url.Content("~/css/themes.css")">
<link rel="stylesheet" href="@Url.Content("~/css/datepicker.css")">
<link rel="stylesheet" href="@Url.Content("~/css/font-face.css")">
<link rel="stylesheet" href="@Url.Content("~/css/pages.css")">
<link rel="stylesheet" href="@Url.Content("~/css/rtl.css")">
<link rel="stylesheet" href="@Url.Content("~/css/select2.css")">
<link rel="stylesheet" href="@Url.Content("~/css/style.min.css")">
<link rel="stylesheet" href="@Url.Content("~/css/summernote-bs3.css")">
<link rel="stylesheet" href="@Url.Content("~/css/pixel-admin.css")">