Sabemi/Sabemi.Admin/Controllers/BlockedAccessController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sabemi.Admin.Models;
using Sabemi.Domain.Interfaces;
using Sabemi.Domain.Interfaces.Services.Admin;

namespace Sabemi.Admin.Controllers
{
    public class BlockedAccessController : MainController
    {
        private readonly ILogger<BlockedAccessController> _logger;
        private readonly IBlockedAccessService _service;

        public BlockedAccessController(INotification notification,
                                       ILogger<BlockedAccessController> logger,
                                       IBlockedAccessService service) : base(notification)
        {
            _logger = logger;
            _service = service;
        }

        [Route("acessos_bloqueados")]
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> List(JQueryDataTableParamModel param)
        {
            List<string[]> data = new List<string[]>();
            string filter = param.sSearch ?? string.Empty;

            try
            {
                int start = param.iDisplayStart + 1;
                int end = param.iDisplayStart + param.iDisplayLength;

                var result = await _service.GetAll(filter, start, end);

                foreach (var item in result)
                {
                    var status = item.Sta_Ativo ? 0 : 1;

                    data.Add(new string[]
                    {
                        item.Dta_Activation_Date.DateTime.ToShortDateString(),
                        item.Dta_Activation_Date.DateTime.ToShortTimeString(),
                        Convert.ToUInt64(item.Cod_Cpf).ToString(@"000\.000\.000\-00"),
                        item.Cod_Ip,
                        string.Empty,
                        item.Cod_Id + "#" + status.ToString()
                    });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            JsonResult retorno = Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = data.Count,
                iTotalDisplayRecords = await _service.GetTotalRecords(filter),
                aaData = data
            });

            return retorno;
        }

        [HttpGet]
        public async Task Blocked(string id, bool inativo)
        {
            var client = await _service.GetBlockedAccess(id);
            client.Sta_Ativo = !inativo;
            await _service.Update(client);
        }
    }
}

Sabemi/Sabemi.Admin/Views/BlockedAccess/Index.cshtml
@{
    ViewBag.Title = " Acessos Bloqueados";
}

<div class="page-header">
    <div class="row">
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-list-ul page-header-icon"></i>@ViewBag.Title</h1>
    </div>
</div>

<div class="table-primary">
    <div class="hidden" id="jq-datatable-caption">Lista de @ViewBag.Title</div>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatable">
        <thead>
            <tr>
                <th width="100">Data</th>
                <th width="40">Hora</th>
                <th width="100">CPF</th>
                <th width="150">IP</th>
                <th width="40">Expira em</th>
                <th width="40">Bloqueado</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<script type="text/javascript">
    init.push(function () {

        $('#jq-datatable').on("draw.dt", function () {
            $('#jq-datatable .chk-inativar').on("click", function () {
                if ($(this).data("inativo") == 0) {
                    $(this).data("inativo", "1");
                }
                else {
                    $(this).data("inativo", "0");
                }
                var inativar = $(this).data("inativo") == 0 ? "false" : "true";
                var url = "@Url.Action("Blocked", "BlockedAccess")/" + $(this).data("id") + "?inativo=" + inativar;

                $.getJSON(url, function (result) {
                    //var typeMessage = result.Success ? "Success" : "Error";
                    //notify(result.Message, typeMessage);
                });
            });
            $('#jq-datatable .switcher-example-default').switcher();
        });

        $('#jq-datatable').dataTable({
            "bServerSide": true,
            "sAjaxSource": "@Url.Action("List", "BlockedAccess")",
            "bProcessing": true,
            "aoColumns": [
                { "sName": "Data", "bSortable": false },
                { "sName": "Hora", "bSortable": false },
                { "sName": "CPF", "bSortable": false },
                { "sName": "IP", "bSortable": false },
                { "sName": "ExpiraEm", "bSortable": false },
                {
                    "sName": "Bloqueado",
                    "bSortable": false,
                    "bSearchable": false,
                    "mRender": function (data, type, full) {
                        var idinativo = data.split("#");
                        return '<input type="checkbox" data-id="' + idinativo[0] + '" data-inativo="' + idinativo[1] + '" ' + (idinativo[1] == "0" ? 'checked="checked"' : '') + ' class="chk-inativar switcher-example-default" /> ';
                    }
                }
            ]
        });
    });
</script>