Sabemi/Sabemi.Admin/Controllers/PortalClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sabemi.Admin.Models;
using Sabemi.Domain.Interfaces;
using Sabemi.Domain.Interfaces.Services.Admin;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Sabemi.Admin.Controllers
{
    public class PortalClientController : MainController
    {
        private readonly IPortalClientService _service;
        private readonly ILogger<PortalClientController> _logger;

        public PortalClientController(INotification notification, IPortalClientService service,
                                      ILogger<PortalClientController> logger) : base(notification)
        {
            _service = service;
            _logger = logger;
        }

        [Route("clientes_portal")]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(JQueryDataTableParamModel param)
        {
            List<string[]> data = new List<string[]>();
            string filter = param.sSearch ?? string.Empty;

            try
            {
                int start = param.iDisplayStart + 1;
                int end = param.iDisplayStart + param.iDisplayLength;
                var result = await _service.GetAll(filter, start, end);                                        

                foreach (var item in result)
                {
                    int blocked = item.Sta_Desativacao ? 0 : 1;

                    ulong cpf = 0;
                    if (!UInt64.TryParse(item.Num_Cpf, out cpf))
                        continue;

                    data.Add(new string[]
                    {
                        cpf.ToString(@"000\.000\.000\-00"), 
                        item.Num_Cpf + "#" + blocked.ToString()
                    });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            JsonResult retorno = Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = data.Count,
                iTotalDisplayRecords = await _service.GetTotalRecords(filter),                
                aaData = data
            });

            return retorno;
        }


        [HttpGet]
        public async Task Blocked(string id, bool inativo)
        {
            var client = await _service.GetClient(id);
            client.Sta_Desativacao = !inativo;
            await _service.Update(client);
        }
    }
}

Sabemi/Sabemi.Admin/Views/PortalClient/Index.cshtml
@{
    ViewBag.Title = " Clientes do Portal";
}

<div class="page-header">
    <div class="row">
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-users page-header-icon"></i>@ViewBag.Title</h1>        
    </div>
</div>

<div class="table-primary">
    <div class="hidden" id="jq-datatable-caption">Lista de @ViewBag.Title</div>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatable">
        <thead>
            <tr>
                <th>CPF</th>
                <th width="40">Bloqueado</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<script type="text/javascript">
    init.push(function () {

        $('#jq-datatable').on("draw.dt", function () {
            $('#jq-datatable .chk-inativar').on("click", function () {
                if ($(this).data("inativo") == 0) {
                    $(this).data("inativo", "1");
                }
                else {
                    $(this).data("inativo", "0");
                }
                var inativar = $(this).data("inativo") == 0 ? "false" : "true";
                var url = "@Url.Action("Blocked", "PortalClient")/" + $(this).data("id") + "?inativo=" + inativar;

                $.getJSON(url, function (result) {
                    //var typeMessage = result.Success ? "Success" : "Error";
                    //notify(result.Message, typeMessage);
                });
            });
            $('#jq-datatable .switcher-example-default').switcher();
        });

        $('#jq-datatable').dataTable({
            "bServerSide": true,
            "sAjaxSource": "@Url.Action("List", "PortalClient")",
            "bProcessing": true,
            "aoColumns": [
                { "sName": "CPF", "bSortable": false },
                {
                    "sName": "Bloqueado",
                    "bSortable": false,
                    "bSearchable": false,
                    "mRender": function (data, type, full) {
                        var idinativo = data.split("#");
                        return '<input type="checkbox" data-id="' + idinativo[0] + '" data-inativo="' + idinativo[1] + '" ' + (idinativo[1] == "0" ? 'checked="checked"' : '') + ' class="chk-inativar switcher-example-default" /> ';
                    }
                }
            ]
        });
    });
</script>